<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      let promisses = new Promise((resolve, reject) => {
        let val = "ankush";
        setTimeout(() => {
          resolve(val);
        }, 200);
      });
      promisses
        .then((result) => {
          console.log(result);
        })
        .catch((error) => {
          console.log(error);
        });

      let promise = new Promise((resolve, reject) => {
        let error = new Error("Something went wrong!");
        setTimeout(() => {
          reject(error);
        }, 200);
      });

      promise
        .then((result) => {
          console.log("Resolved:", result);
        })
        .catch((error) => {
          console.log("Rejected:", error.message);
        });

      function getData() {
        return new Promise((resolve, reject) => {
          setTimeout(() => {
            const randomNumber = Math.random();
            if (randomNumber > 0.5) {
              resolve(randomNumber);
            } else {
              reject(new Error("Failed to get data"));
            }
          }, 1000);
        });
      }

      // Using Promise.all to handle multiple promises
      const promises = [getData(), getData(), getData()];

      Promise.all(promises)
        .then((values) => {
          console.log("All promises resolved:", values);
        })
        .catch((error) => {
          console.error(
            "Error occurred in one of the promises:",
            error.message
          );
        });

      // Using Promise.race to handle the fastest promise
      const fastestPromise = Promise.race(promises);

      fastestPromise
        .then((value) => {
          console.log("Fastest promise resolved:", value);
        })
        .catch((error) => {
          console.error(
            "Error occurred in the fastest promise:",
            error.message
          );
        });

      // Using Promise.resolve to create a resolved promise with a value
      const resolvedPromise = Promise.resolve("Resolved value");

      resolvedPromise.then((value) => {
        console.log("Resolved promise:", value);
      });

      // Using Promise.reject to create a rejected promise with an error
      const rejectedPromise = Promise.reject(new Error("Rejected error"));

      rejectedPromise.catch((error) => {
        console.error("Rejected promise:", error.message);
      });

      const ab = async () => {
        const promise = new Promise((resolve, reject) => {
          let a = "ankush";
          setTimeout(() => {
            if (a) {
              resolve(a);
            } else {
              reject(error);
            }
          }, 2000);
        });
        const result = await promise;
        console.log(result).catch(error);
        console.log(error);
      };
      ab();
    </script>
  </body>
</html>
